import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F8',
    paddingVertical: 30,
  },
  navbar: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 30
  },
  icons: {
    marginRight: 75,
    color: 'black',
    fontSize: 30,
  },
  titleNavbar: {
    fontFamily: 'Poppins-Bold',
    fontWeight: 'bold',
    color: 'black',
    fontSize: 20,
    marginLeft: 30,
  },
  all_container: {
    marginLeft: '10%',
    width: '80%',
    marginTop: '5%',
  },
  container_up: {
    alignItems: 'center',
  },
  input: {
    borderBottomWidth: 1,
    borderColor: `#BCBABA`,
    borderWidth: 0,
    fontFamily: 'Poppins',
    fontSize: 10,
    height: 40,
    margin: 12,
    outlineWidth: 4,
    padding: 10,
    width: `80%`,
    color: 'black',
    textAlign: 'center',
    fontWeight: '400',
  },
  input_bottom: {
    borderBottomWidth: 1,
    borderColor: `#BCBABA`,
    borderWidth: 0,
    fontFamily: 'Poppins',
    fontSize: 15,
    height: 40,
    marginTop:10,
    marginBottom:10,
    outlineWidth: 4,
    padding: 10,
    width: `90%`,
    color: 'black',
    fontWeight: '400',
  },
  text: {
    color: `black`,
    fontFamily: `Poppins`,
    fontSize: 18,
    fontWeight: '900',
  },
  image: {
    borderRadius: 200,
    width: 150,
    height: 150,
    padding: 100,
    marginTop:10,
  },
  radio: {
    display: 'flex',
    flexDirection: 'row',
    marginRight: 20,
    alignItems: 'center',
    marginVertical: 30,
  },
  checkedOuter: {
    width: 20,
    height: 20,
    borderColor: '#6A4029',
    borderWidth: 2,
    borderRadius: 100,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  checkedInner: {
    backgroundColor: '#6A4029',
    width: 10,
    height: 10,
    borderRadius: 50,
  },
  unchekedOuter: {
    width: 20,
    height: 20,
    borderColor: '#9F9F9F',
    borderWidth: 2,
    borderRadius: 100,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkedText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    color: 'black',
    marginLeft: 5,
    paddingTop: 3.5,
  },
  uncheckedText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 15,
    color: '#9F9F9F',
    marginLeft: 15,
    paddingTop: 3.5,
  },
});

export default styles;